library(DESeq2)
INPUT_1 <-  read.table("N1-input_HTcount.txt",sep ="\t",row.names = 1)
INPUT_2 <-  read.table("N2-input_HTcount.txt",sep ="\t",row.names = 1)

IP_1 <-  read.table("T1-input_HTcount.txt",sep ="\t",row.names = 1)
IP_2 <-  read.table("T2-input_HTcount.txt",sep ="\t",row.names = 1)

all <- cbind(IP_1,IP_2,INPUT_1,INPUT_2)
head(all)
all <- as.matrix(all)
class(all)
colnames(all)
colnames(all) <- c("IP_1","IP_2","INPUT_1","INPUT_2")
head(all)
conditions <- factor(c("IP","IP","INPUT","INPUT"))
class(conditions)
conditions
dds <- DESeqDataSetFromMatrix(all, DataFrame(conditions), ~ conditions)
dds<-dds[rowSums(counts(dds))>1,]
head(all)
summary(all)
dds$conditions <- relevel(dds$conditions, "INPUT")
DEGs <- DESeq(dds)
res <- results(DEGs)
head(res)
write.csv(res,file = "ToverN.csv")
rld <- normTransform(DEGs)
exprSet_new=assay(rld)
write.csv(exprSet_new,file = "ToverN_normlization.csv")

diff_gene <-subset(res, pvalue < 0.05)
write.csv(diff_gene, file = "ToverN_0.05.csv")
up_gene<-subset(diff_gene,diff_gene$log2FoldChange >= 1.0)
write.csv(up_gene,file = "ToverN_upFC.csv")
down_gene<-subset(diff_gene,diff_gene$log2FoldChange <= -1.0)
write.csv(down_gene,file = "ToverN_downFC.csv")
